SZTOS/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('judge.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
]

handler404 = 'judge.views.handler404'

judge/urls.py
from django.urls import path

from . import views

app_name = 'judge'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('courses/', views.CourseListView.as_view(), name='courses'),
    path('course/add/', views.CourseCreate.as_view(), name='course_create'),
    path('course/<int:course_pk>/update/', views.CourseUpdate.as_view(), name='course_update'),
    path('course/<int:course_pk>/students/add', views.CourseAddStudents.as_view(), name='course_add_students'),
    path('course/<int:course_pk>/delete/', views.CourseDelete.as_view(), name='course_delete'),
    path('course/<int:course_pk>/problems/', views.ProblemListView.as_view(), name='problems'),
    path('course/<int:course_pk>/grades/', views.CourseGrades.as_view(), name='course_grades'),
    path('course/<int:course_pk>/grades.csv', views.course_grades_csv, name='course_grades_csv'),
    path('course/<int:course_pk>/students/', views.StudentListView.as_view(), name='students'),
    path('course/<int:course_pk>/students/remove/', views.remove_user, name='remove_users'),
    path('course/<int:course_pk>/problem/add/', views.ProblemCreate.as_view(), name='problem_create'),
    path('course/<int:course_pk>/problem/<int:problem_pk>/update/',
         views.ProblemUpdate.as_view(), name='problem_update'),
    path('course/<int:course_pk>/problem/<int:problem_pk>/delete/',
         views.ProblemDelete.as_view(), name='problem_delete'),
    path('course/<int:course_pk>/problem/<int:problem_pk>/', views.ProblemDetailView.as_view(), name='detail'),
    path('course/<int:course_pk>/problem/<int:problem_pk>/solution/<int:solution_pk>/source/',
         views.SourceCodeView.as_view(), name='source_code'),
    path('course/<int:course_pk>/problem/<int:pk>/grades/', views.ProblemGradesView.as_view(), name='problem_grades'),
    path('course/<int:course_pk>/problem/<int:problem_pk>/tests/',
         views.TestCaseView.as_view(), name='test_cases'),
    path('course/<int:course_pk>/problem/<int:problem_pk>/test/add/',
         views.TestCaseCreate.as_view(), name='test_case_create'),
    path('course/<int:course_pk>/problem/<int:problem_pk>/test/<int:test_case_pk>/update/',
         views.TestCaseUpdate.as_view(), name='test_case_update'),
    path('course/<int:course_pk>/problem/<int:problem_pk>/test/<int:test_case_pk>/delete/',
         views.TestCaseDelete.as_view(), name='test_case_delete'),
    path('course/<int:course_pk>/problem/<int:problem_pk>/solution/<int:solution_pk>/download/',
         views.download_solution, name='download_solution'),
    path('course/<int:course_pk>/problem/<int:problem_pk>/solutions/download/',
         views.download_all_solutions, name='download_all_solutions'),
    path('course/<int:course_pk>/problem/<int:problem_pk>/solution/send/', views.send_solution, name='send'),
]

judge/models.py
from typing import Dict, Optional
from uuid import uuid4

from django.conf import settings
from django.contrib.auth.models import User
from django.core.files import File
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Sum, Q, Subquery, Max

from judge.storage import s3, get_directory


class Course(models.Model):
    name = models.CharField(max_length=100)
    assigned_users = models.ManyToManyField(User)

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ("remove_user", "Can remove user"),
            ("view_all_courses", "Can view all courses")
        )


class Problem(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="problems")
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def __str__(self):
        return self.title

    def get_solutions(self) -> Dict[User, "Solution"]:
        newest = Subquery(self.solution_set.values("user__pk").annotate(Max("pk")).values("pk__max"))
        solutions = Solution.objects.filter(pk__in=newest).order_by("user__pk")

        return {
            solution.user: solution for solution in solutions
        }

    def run_all_solutions(self) -> None:
        newest = Subquery(self.solution_set.values("user__pk").annotate(Max("pk")).values("pk__max"))
        solutions = Solution.objects.filter(pk__in=newest).order_by("user__pk")
        for solution in solutions:
            from judge.tasks import validate_solution
            TestRun.objects.filter(solution=solution).delete()
            validate_solution.delay(solution.id)

    class Meta:
        permissions = (
            ("view_grades", "Can view grades"),
        )


class TestCase(models.Model):
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE, related_name="test_cases")
    input = models.TextField(blank=True)
    expected_output = models.TextField()
    points = models.FloatField(default=1, validators=(MinValueValidator(0),))
    memory_limit = models.IntegerField(blank=True, default=50 * 1024 * 1024)
    time_limit = models.FloatField(validators=(MinValueValidator(0),), blank=True, default=60)


class Solution(models.Model):
    class Meta:
        permissions = (
            ("view_all_solutions", "Can view all solutions"),
        )

    class State(models.IntegerChoices):
        COMPILATION_PENDING = 0
        COMPILATION_IN_PROGRESS = 1
        COMPILATION_SUCCESSFUL = 2
        COMPILATION_FAILED = 3

    class Language(models.IntegerChoices):
        CPP = 0, "C++"
        PYTHON = 1

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="solutions", default=None)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    state = models.IntegerField(choices=State.choices, default=State.COMPILATION_PENDING)
    uuid = models.UUIDField(default=uuid4, editable=False)
    language = models.IntegerField(choices=Language.choices)

    def save_file(self, file: File) -> None:
        s3.put_object(settings.S3_SUBMISSION_BUCKET, f"{self.uuid}/files/{file.name}", file, file.size)

    def get_sources(self) -> Dict[str, str]:
        return get_directory(settings.S3_SUBMISSION_BUCKET, f"{self.uuid}/files/")

    def get_grade(self) -> Optional[float]:
        if self.test_runs.count() == 0:
            return None

        aggregated = self.test_runs.all().aggregate(
            max_points=Sum("test_case__points"),
            points=Sum("test_case__points", filter=Q(state=TestRun.State.VALID)),
        )

        if aggregated["max_points"] == 0:
            return None

        if aggregated["points"] is None:
            return 0

        return aggregated["points"] / aggregated["max_points"]

    def __str__(self):
        return f"Solution({self.id})"


class TestRun(models.Model):
    class State(models.IntegerChoices):
        VALID = 0
        CRASHED = 1
        INVALID = 2
        TIMED_OUT = 3
        PENDING = 4

    test_case = models.ForeignKey(TestCase, on_delete=models.CASCADE)
    solution = models.ForeignKey(Solution, on_delete=models.DO_NOTHING, related_name="test_runs")
    stdout = models.TextField(null=True)
    stderr = models.TextField(null=True)
    return_code = models.IntegerField(null=True)
    state = models.IntegerField(choices=State.choices, default=State.PENDING)
    time = models.FloatField(null=True)

judge/views.py
import csv
from io import BytesIO, StringIO
from zipfile import ZipFile, ZIP_DEFLATED

from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.http import require_POST, require_GET
from django.views.generic.edit import FormMixin

from .forms import SendSolutionForm, ProblemForm, TestCaseForm, CourseCreateUpdateForm, StudentForm, \
    CourseAddStudentsForm
from .models import Course, Problem, Solution, TestCase
from .tasks import validate_solution


class IndexView(generic.TemplateView):
    template_name = 'judge/index.html'


@method_decorator(permission_required('judge.view_course'), name='dispatch')
class CourseListView(generic.ListView):
    template_name = 'judge/courses.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        if self.request.user.has_perm('judge.view_all_courses'):
            return Course.objects.all()
        else:
            return Course.objects.filter(assigned_users__id=self.request.user.id)


@method_decorator(permission_required('judge.add_course'), name='dispatch')
class CourseCreate(generic.CreateView):
    template_name = 'judge/course_create.html'
    form_class = CourseCreateUpdateForm
    success_url = reverse_lazy('judge:courses')

    def form_valid(self, form):
        obj = form.save(commit=True)
        users = form.cleaned_data['student_list'].split()
        for user in users:
            student = User.objects.filter(username=user).first()
            if student:
                obj.assigned_users.add(student.id)
        obj.save()
        return super().form_valid(form)


@method_decorator(permission_required('judge.change_course'), name='dispatch')
class CourseUpdate(generic.UpdateView):
    template_name_suffix = '_update'
    form_class = CourseCreateUpdateForm
    pk_url_kwarg = 'course_pk'

    def get_queryset(self):
        return Course.objects.filter(id=self.kwargs.get('course_pk'))

    def form_valid(self, form):
        obj = form.save(commit=True)
        obj.assigned_users.clear()
        users = form.cleaned_data['student_list'].split()
        for user in users:
            student = User.objects.filter(username=user).first()
            if student:
                obj.assigned_users.add(student.id)
        obj.save()
        return super().form_valid(form)

    def get_success_url(self):
        course = get_object_or_404(Course, id=self.kwargs.get('course_pk'))
        return reverse('judge:problems', args=[course.id])


@method_decorator(permission_required('judge.change_course'), name='dispatch')
class CourseAddStudents(generic.UpdateView):
    template_name_suffix = '_add_students'
    form_class = CourseAddStudentsForm
    pk_url_kwarg = 'course_pk'
    label = 'test'

    def get_queryset(self):
        return Course.objects.filter(id=self.kwargs.get('course_pk'))

    def form_valid(self, form):
        obj = form.save(commit=True)
        users = form.cleaned_data['student_list'].split()
        for user in users:
            student = User.objects.filter(username=user).first()
            if student:
                obj.assigned_users.add(student.id)
        obj.save()
        return super().form_valid(form)

    def get_success_url(self):
        course = get_object_or_404(Course, id=self.kwargs.get('course_pk'))
        return reverse('judge:students', args=[course.id])


@method_decorator(permission_required('judge.delete_course'), name='dispatch')
class CourseDelete(generic.DeleteView):
    template_name_suffix = '_delete'
    model = Course
    success_url = reverse_lazy('judge:courses')
    pk_url_kwarg = 'course_pk'


@method_decorator(permission_required('judge.view_grades'), name='dispatch')
class CourseGrades(generic.DetailView):
    template_name_suffix = '_grades'
    model = Course
    pk_url_kwarg = 'course_pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        grades = {}
        problems = self.object.problems.all()
        users = self.object.assigned_users.all()

        for problem in problems:
            solutions = problem.get_solutions()
            for user in users:
                if solutions.get(user):
                    grade = solutions[user].get_grade()
                else:
                    grade = 0

                if user in grades:
                    grades[user].append(grade)
                else:
                    grades[user] = [grade]

        context['problems'] = problems
        context['user_grades'] = grades
        return context


@method_decorator(permission_required('judge.remove_user'), name='dispatch')
class StudentListView(generic.UpdateView):
    form_class = StudentForm
    template_name = 'judge/students.html'
    pk_url_kwarg = 'course_pk'

    def get_queryset(self):
        return Course.objects.filter(id=self.kwargs.get('course_pk'))

    def get_success_url(self):
        course = get_object_or_404(Course, id=self.kwargs.get('course_pk'))
        return reverse('judge:problems', args=[course.id])


@method_decorator(permission_required('judge.view_problem'), name='dispatch')
class ProblemListView(generic.ListView):
    template_name = 'judge/problems.html'
    context_object_name = 'latest_problem_list'

    def get_queryset(self):
        return Problem.objects.filter(course__id=self.kwargs.get('course_pk'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['course'] = Course.objects.get(id=self.kwargs.get('course_pk'))
        return context


@method_decorator(permission_required('judge.add_problem'), name='dispatch')
class ProblemCreate(generic.CreateView):
    template_name = 'judge/problem_create.html'
    model = Problem
    form_class = ProblemForm

    def get_initial(self):
        course = get_object_or_404(Course, id=self.kwargs.get('course_pk'))
        return {'course': course}

    def get_success_url(self):
        course = get_object_or_404(Course, id=self.kwargs.get('course_pk'))
        return reverse('judge:problems', args=[course.id])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['course'] = Course.objects.get(id=self.kwargs.get('course_pk'))
        return context


@method_decorator(permission_required('judge.change_problem'), name='dispatch')
class ProblemUpdate(generic.UpdateView):
    template_name_suffix = '_update'
    model = Problem
    form_class = ProblemForm
    pk_url_kwarg = 'problem_pk'

    def get_initial(self):
        course = get_object_or_404(Course, id=self.kwargs.get('course_pk'))
        return {'course': course}

    def get_success_url(self):
        course = get_object_or_404(Course, id=self.kwargs.get('course_pk'))
        return reverse('judge:problems', args=[course.id])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['course'] = Course.objects.get(id=self.kwargs.get('course_pk'))
        return context


@method_decorator(permission_required('judge.delete_problem'), name='dispatch')
class ProblemDelete(generic.DeleteView):
    template_name_suffix = '_delete'
    model = Problem
    pk_url_kwarg = 'problem_pk'

    def get_success_url(self):
        course = get_object_or_404(Course, id=self.kwargs.get('course_pk'))
        return reverse('judge:problems', args=[course.id])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['course'] = Course.objects.get(id=self.kwargs.get('course_pk'))
        return context


@method_decorator(permission_required('judge.view_problem'), name='dispatch')
class ProblemDetailView(FormMixin, generic.DetailView):
    model = Problem
    form_class = SendSolutionForm
    template_name = 'judge/detail.html'
    pk_url_kwarg = 'problem_pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        solution = Solution.objects.filter(
            user__id=self.request.user.id,
            problem__pk=self.kwargs.get('problem_pk')
        ).last()
        problem = Problem.objects.get(pk=self.kwargs.get('problem_pk'))
        context['user'] = self.request.user
        context['course'] = problem.course
        context['problem'] = problem
        context["solution"] = solution
        if solution:
            context["grade"] = solution.get_grade()

        return context


@method_decorator(permission_required('judge.view_solution'), name='dispatch')
class SourceCodeView(generic.DetailView):
    model = Solution
    template_name = 'judge/source.html'
    pk_url_kwarg = 'solution_pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context['solution'].user != self.request.user and not self.request.user.has_perm("judge.view_all_solutions"):
            raise Http404()

        context['course'] = Course.objects.get(id=self.kwargs.get('course_pk'))
        context['problem'] = Problem.objects.get(id=self.kwargs.get('problem_pk'))

        return context


@method_decorator(permission_required('judge.view_grades'), name='dispatch')
class ProblemGradesView(generic.DetailView):
    model = Problem
    template_name = "judge/problem_grades.html"

    def get_queryset(self):
        return super().get_queryset().filter(course__pk=self.kwargs.get("course_pk"))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['course'] = Course.objects.get(id=self.kwargs.get('course_pk'))
        return context

judge/templates/judge/courses.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}Courses{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Courses' 'judge:courses' %}
{% endblock %}

{% block content %}
    {% render_breadcrumbs %}
    <h2 class="h2 font-weight-normal">Courses</h2>
    {% if perms.judge.add_course %}
        <a class="btn btn-success my-1" href="{% url 'judge:course_create' %}">New course</a>
    {% endif %}
    {% if course_list %}
        <div class="card shadow">
            <div class="table-responsive">
                <table class="table table-hover table-bordered m-0 p-0">
                    <thead class="thead-light">
                    <tr>
                        <th>Course</th>
                        {% if perms.judge.change_course and perms.judge.delete_course %}
                            <th>Edit</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for course in course_list %}
                        <tr>
                            <td class="p-0 align-middle">
                                <a class="nav-link text-dark"
                                   href="{% url 'judge:problems' course.id %}">
                                    {{ course.name }}
                                </a>
                            </td>
                            {% if perms.judge.change_course and perms.judge.delete_course %}
                                <td class="p-0 text-center align-middle">
                                    <a class="btn btn-sm btn-success m-1"
                                       href="{% url 'judge:course_update' course.id %}">Update</a>
                                    <a class="btn btn-sm btn-danger m-1"
                                       href="{% url 'judge:course_delete' course.id %}">Delete</a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <p>No courses are available.</p>
    {% endif %}
{% endblock %}

judge/templates/judge/detail.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}
{% load bootstrap4 %}
{% load filters %}

{% block title %}Detail{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Courses' 'judge:courses' %}
    {% breadcrumb course.name 'judge:problems' course.id %}
    {% breadcrumb problem.title 'judge:detail' course.id problem.id %}
{% endblock %}

{% block content %}
    {% render_breadcrumbs %}
    <h1 class="h1 font-weight-normal">
        {{ problem.title }}{% if perms.judge.change_problem and perms.judge.delete_problem %}
            <a class="btn btn-sm btn-success"
               href="{% url 'judge:problem_update' problem.course.id problem.id %}">Update</a>
            <a class="btn btn-sm btn-danger"
               href="{% url 'judge:problem_delete' problem.course.id problem.id %}">Delete</a>
        {% endif %}
    </h1>
    <h3 class="h3 font-weight-normal">{{ problem.description | markdown | safe }}</h3>
    {% if perms.judge.view_testcase %}
        <a class="btn btn-success my-1"
           href="{% url 'judge:test_cases' course.id problem.id %}">View test cases</a>
    {% endif %}
    {% if perms.judge.view_solution and solution %}
        <a class="btn btn-primary btn-bg"
           href="{% url "judge:source_code" course.id problem.id solution.id %}">Source</a>
    {% endif %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% if perms.judge.add_solution %}
        <div class="d-flex justify-content-left" id="send">
            <form class="form form-vertical" action="{% url 'judge:send' course.id problem.id %}" method="POST"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input class="btn btn-secondary btn-bg" type="submit" value="Send">
            </form>
        </div>
    {% endif %}
    {% if solution %}
        <h2>Status: {{ solution.get_state_display }}</h2>
        {% if solution.test_runs.count > 0 %}
            <h2>Grade: {% if grade is None %}N/A{% else %}{{ grade | percentage }}{% endif %}</h2>
            <div class="card shadow">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered m-0">
                        <thead class="thead-light">
                        <tr>
                            <th>#</th>
                            <th>State</th>
                            <th>Time [s]</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for test_run in solution.test_runs.all %}
                            {% if test_run.get_state_display == 'Valid' %}
                                <tr class="table-success w-auto">
                                    {% elif test_run.get_state_display == 'Pending' %}
                                <tr class="table-info w-auto">
                                    {% else %}
                                <tr class="table-danger w-auto">
                            {% endif %}
                        <td>{{ forloop.counter }}</td>
                        <td class="w-75">{{ test_run.get_state_display }}</td>
                        <td class="w-25">{{ test_run.time }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

judge/templates/judge/index.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}Home{% endblock %}

{% block content %}
    {% render_breadcrumbs %}
    <h1>SZTOS</h1>
    <h2>Home page</h2>
{% endblock %}

judge/templates/judge/problems.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}Problems{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Courses' 'judge:courses' %}
    {% breadcrumb course.name 'judge:problems' course.id %}
{% endblock %}

{% block content %}
    {% render_breadcrumbs %}
    <h2 class="h2 font-weight-normal">{{ course }}
        {% if perms.judge.change_course and perms.judge.delete_course %}
            <a class="btn btn-sm btn-success"
               href="{% url 'judge:course_update' course.id %}">Update</a>
            <a class="btn btn-sm btn-danger"
               href="{% url 'judge:course_delete' course.id %}">Delete</a>
        {% endif %}
    </h2>

    {% if perms.judge.add_problem %}
        <a class="btn btn-success my-1" href="{% url 'judge:problem_create' course.id %}">Add problem</a>
    {% endif %}
    {% if perms.judge.remove_user %}
        <a class="btn btn-primary my-1" href="{% url 'judge:students' course.id %}">Manage students</a>
    {% endif %}
    {% if perms.judge.view_grades %}
        <a class="btn btn-primary my-1" href="{% url 'judge:course_grades' course.id %}">View grades</a>
    {% endif %}

    {% if latest_problem_list %}
        <div class="card shadow">
            <div class="table-responsive">
                <table class="table table-hover table-bordered m-0 p-0">
                    <thead class="thead-light">
                    <tr>
                        <th>Problem</th>
                        {% if perms.judge.view_grades %}
                            <th>Grades</th>
                        {% endif %}
                        {% if perms.judge.change_problem and perms.judge.delete_problem %}
                            <th>Edit</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for problem in latest_problem_list %}
                        <tr>
                            <td class="p-0 align-middle">
                                <a class="nav-link text-dark"
                                   href="{% url 'judge:detail' problem.course.id problem.id %}">
                                    {{ problem.title }}
                                </a>
                            </td>
                            {% if perms.judge.view_grades %}
                                <td class="w-auto p-0 mx-1 text-center align-middle">
                                    <a class="btn btn-sm btn-primary"
                                       href="{% url 'judge:problem_grades' problem.course.id problem.id %}">Grades</a>
                                </td>
                            {% endif %}
                            {% if perms.judge.change_problem and perms.judge.delete_problem %}
                                <td class="w-auto p-0 mx-1 text-center align-middle">
                                    <a class="btn btn-sm btn-success m-1"
                                       href="{% url 'judge:problem_update' problem.course.id problem.id %}">Update</a>
                                    <a class="btn btn-sm btn-danger m-1"
                                       href="{% url 'judge:problem_delete' problem.course.id problem.id %}">Delete</a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <p>No problems are available.</p>
    {% endif %}
{% endblock %}

judge/templates/judge/source.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}
{% load bootstrap4 %}
{% load filters %}

{% block title %}Source{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Courses' 'judge:courses' %}
    {% breadcrumb course.name 'judge:problems' course.id %}
    {% breadcrumb problem.title 'judge:detail' course.id problem.id %}
    {% breadcrumb 'Source' 'judge:source_code' course.id problem.id solution.id %}
{% endblock %}

{% block content %}
    {% render_breadcrumbs %}
    <h1>{{ problem.title }}</h1>
    <h2>{{ problem.description | markdown | safe }}</h2>
    {% if solution %}
        <h2>Status: {{ solution.get_state_display }}</h2>
        <a class="btn btn-primary btn-bg"
           href="{% url "judge:download_solution" course.id problem.id solution.pk %}">Download</a>
        {% for name, source in solution.get_sources.items %}
            <div class="card shadow my-1 source">
                <article class="card-body">
                    <div class="form-group ">
                        <label for="exampleFormControlTextarea1">{{ name }}</label>
                        <pre><code><textarea disabled class="form-control"
                                             id="exampleFormControlTextarea1"
                                             rows="15">{{ source }}</textarea></code></pre>
                    </div>
                </article>
            </div>
        {% endfor %}
        <label for="solution{{ solution.id }}">Added {{ solution.pub_date }}</label><br>
    {% endif %}
{% endblock %}

judge/templates/judge/testcases.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}Test cases{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Courses' 'judge:courses' %}
    {% breadcrumb course.name 'judge:problems' course.id %}
    {% breadcrumb problem.title 'judge:detail' course.id problem.id %}
    {% breadcrumb 'Test cases' 'judge:test_cases' course.id problem.id %}
{% endblock %}

{% block content %}
    {% render_breadcrumbs %}
    <h1 class="h3 font-weight-normal">{{ problem }}</h1>
    <a class="btn btn-success my-1"
       href="{% url 'judge:test_case_create' problem.course.id problem.id %}">Add test case</a>
    {% if test_cases_list %}
        <div class="card shadow">
            <div class="table-responsive">
                <table class="table table-bordered m-0">
                    <thead class="thead-light">
                    <tr>
                        <th>#</th>
                        <th>Input</th>
                        <th>Expected output</th>
                        <th>Points</th>
                        <th>Memory limit</th>
                        <th>Time limit</th>
                        <th>Edit</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for test_case in test_cases_list %}
                        <tr>
                            <td class="w-auto text-center">{{ forloop.counter }}</td>
                            <td class="w-25 text-center">{{ test_case.input }}</td>
                            <td class="w-25 text-center">{{ test_case.expected_output }}</td>
                            <td class="w-auto text-center">{{ test_case.points }}</td>
                            <td class="w-auto text-center">{{ test_case.memory_limit }}</td>
                            <td class="w-auto text-center">{{ test_case.time_limit }}</td>
                            <td class="w-auto text-center align-middle p-0">
                                <a class="btn btn-sm btn-success m-1"
                                   href="{% url 'judge:test_case_update' test_case.problem.course.id test_case.problem.id test_case.id %}"
                                >Update</a>
                                <a class="btn btn-sm btn-danger m-1"
                                   href="{% url 'judge:test_case_delete' test_case.problem.course.id test_case.problem.id test_case.id %}"
                                >Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <p>No test cases are available.</p>
    {% endif %}
{% endblock %}